[package]
name = "slap_vm"
version = "0.2.0"
authors = ["taquarius"]
description = "This crate is available for ownership transfer"
license = "MIT"
repository = "https://github.com/taquarius/slap_vm"
homepage = "https://github.com/taquarius/slap_vm"
edition = "2021"
